@cinema_be_HostAddress = http://localhost:5092
POST http://localhost:5092/api/Account/login
Content-Type: application/json

{
    "username": "testUser",
    "password": "testPassword123!",
    "rememberMe": true
}


