@cinema_be_HostAddress = http://localhost:5092

POST {{cinema_be_HostAddress}}/api/account/register/
Content-Type: application/json

{
    "username": "testUser",
    "password": "testPassword123!",
    "email": "testEmail@gmail.com"
}


