
@cinema_be_HostAddress = http://localhost:5092
POST https://localhost:7046/api/Admin/create-movie
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOlsiTWVtYmVyIiwiQWRtaW4iXSwiZXhwIjoxNzM5MjIwMjc0fQ.kTJQYlfqbefrrfUKCn9f_LnV-x-TT71p5TUh1VA1BKyreoy_F4ncYE6QBWpaZKnZUwZZrr4-cYBCJCfy9mtevQ

{
  "title": "Inception",
  "description": "A mind-bending thriller where dream invasion is possible.",
  "duration": "02:28:00",
  "country": "USA",
  "genre": "Sci-Fi",
  "releaseDate": "2010-07-16",
  "endDate": null,
  "director": "Christopher Nolan",
  "cast": "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page",
  "rating": 8.8,
  "trailerUrl": "https://www.youtube.com/watch?v=YoHD9XEInc0",
  "imageUrl": "https://example.com/inception.jpg",
  "sessions": null
}


